doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        #driver 'pdo_mysql'
        #server_version: '5.7'
        #chaset: utf8mb4

        #IMPORTANT: You MUST configure your server version,
        #
        #
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          Apps:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App